apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rita-v2-baseapp-02.fullname" . }}
  labels:
    {{- include "rita-v2-baseapp-02.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "rita-v2-baseapp-02.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rita-v2-baseapp-02.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: http
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: http
          env:
            - name: DATABASE_HOST
              value: {{ .Values.database.host | quote }}
            - name: DATABASE_PORT
              value: {{ .Values.database.port | quote }}
            {{- if .Values.otel.enabled }}
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: {{ .Values.otel.exporter.traces.endpoint | quote }}
            - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
              value: {{ .Values.otel.exporter.metrics.endpoint | quote }}
            {{- end }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "rita-v2-baseapp-02.fullname" . }}
                  key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "rita-v2-baseapp-02.fullname" . }}
                  key: DATABASE_PASSWORD
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "rita-v2-baseapp-02.fullname" . }}
                  key: DATABASE_NAME
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "rita-v2-baseapp-02.fullname" . }}
                  key: JWT_SECRET
            - name: SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "rita-v2-baseapp-02.fullname" . }}
                  key: SUPABASE_URL
            - name: SUPABASE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "rita-v2-baseapp-02.fullname" . }}
                  key: SUPABASE_KEY
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
