{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "rita-v2-baseapp-02.fullname" . }}
  labels:
    {{- include "rita-v2-baseapp-02.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: {{ .Values.externalSecrets.secretStoreKind }}
  target:
    name: {{ include "rita-v2-baseapp-02.fullname" . }}
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_USER
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRef.key }}
        property: DATABASE_USER
    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRef.key }}
        property: DATABASE_PASSWORD
    - secretKey: DATABASE_NAME
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRef.key }}
        property: DATABASE_NAME
    - secretKey: JWT_SECRET
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRef.key }}
        property: JWT_SECRET
    - secretKey: SUPABASE_URL
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRef.key }}
        property: SUPABASE_URL
    - secretKey: SUPABASE_KEY
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRef.key }}
        property: SUPABASE_KEY
{{- end }}
