{{- if not .Values.externalSecrets.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rita-v2-baseapp-02.fullname" . }}
  labels:
    {{- include "rita-v2-baseapp-02.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_USER: {{ .Values.secrets.DATABASE_USER | b64enc | quote }}
  DATABASE_PASSWORD: {{ .Values.secrets.DATABASE_PASSWORD | b64enc | quote }}
  DATABASE_NAME: {{ .Values.secrets.DATABASE_NAME | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | b64enc | quote }}
  SUPABASE_URL: {{ .Values.secrets.SUPABASE_URL | b64enc | quote }}
  SUPABASE_KEY: {{ .Values.secrets.SUPABASE_KEY | b64enc | quote }}
{{- end }}
