name: Delivery
on:
  workflow_run:
    workflows: [ "Release" ]
    branches: [ main ]
    types:
      - completed
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag to build and push (e.g., v0.0.2)'
        required: true
        type: string
jobs:
  Delivery:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    name: Delivery
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Extract Release Version
        id: get_release_version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION=$(git describe --tags --abbrev=0)
          fi
          if [ -z "$VERSION" ]; then
            echo "Error: No version found!" && exit 1
          fi
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
      - name: Build Docker Image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}
          IMAGE_NAME_LOWER=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')
          docker build -t $IMAGE_NAME_LOWER:${{ env.RELEASE_VERSION }} .
          docker tag $IMAGE_NAME_LOWER:${{ env.RELEASE_VERSION }} $IMAGE_NAME_LOWER:latest
      - name: Push Docker Image to GitHub Container Registry (GHCR)
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}
          IMAGE_NAME_LOWER=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')
          docker push $IMAGE_NAME_LOWER:${{ env.RELEASE_VERSION }}
          docker push $IMAGE_NAME_LOWER:latest